stages:
  - build
  - deploy

build-nodejs:
  stage: build
  tags:
    - web
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

deploy-nodejs:
  stage : deploy
  tags:
    - web
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker run -d -p 8080:80 --restart unless-stopped "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

